### ISSUE TITLE
SaveRecords saves only one record for TaxRate class

### ISSUE THREAD

**Issue by geekdeepak** [waynerobinson/xeroizer#304]

**Comment by rjaus** [comment]
save should be called on a specific tax rate, rather than a group of tax rates.

Correct usage would be:

TaxRate = xero.TaxRate.all.first
TaxRate.effective_rate = 2.0
TaxRate.save

Note: It's probably going to raise a validation error, unless you created the TaxRate yourself (system defined tax rates can not be modified).
