### ISSUE TITLE
Issue when creating a new invoice

### ISSUE THREAD

**Issue by normancapule** [waynerobinson/xeroizer#40]
Hi! I'm having this error: Xeroizer::ApiException: Xeroizer::ApiException when I try to create a new Invoice with only two attributes, contact and type.

Also, i'm using a private application as the xero_client.

Here were the steps I took that resulted to this error:
1. xero_client = Xeroizer::PrivateApplication.new(key, secret, private_key_path)
(I confirmed this to be working by calling xero_client.Contact.all)

2, temp = xero_client.Invoice.build :type => "ACCPAY"
1. temp.contact = xero_client.Contact.find(client.id).download_complete_record!
   (I confirmed that the contact was found)
2. temp.save
3. Error

I hope to hear your reply about this issue soon! Thanks!

**Comment by rjaus** [comment]
Invoice model now contains a number of validations, feel free to add more: https://github.com/waynerobinson/xeroizer/blob/master/lib/xeroizer/models/invoice.rb

**Comment by smingins** [comment]
@RileyJamesXero why has this issue been closed?  I was tracking down why we were getting to exceptions trying to create an invoice and it was due to:

`
<ValidationErrors>
  <ValidationError>
    <Message>One or more line items must be specified</Message>
  </ValidationError>
</ValidationErrors>
`
But all this gem does it return false for the error with no explanation.

What am I missing here?
