### ISSUE TITLE
OAuth 2 support?

### ISSUE THREAD

**Issue by stuartgibson** [waynerobinson/xeroizer#493]
Xero have announced that from December 1st 2019 you will no longer be able to create OAuth 1.0a applications and all new apps will need to use OAuth 2.0. Are there plans for Xeroizer to support this as I can't see any reference in documentation or current code.

**Comment by AndyWendt** [comment]
[Mavenlink](https://github.com/mavenlink) is working on this over on our own fork though it won't be generally releasable for a bit since we're only going to be supporting providing an `access_token` and `refresh_token` for the next little bit. Consider this to be a work in progress for the near future.  

[oauth2 functionality](https://github.com/mavenlink/xeroizer/tree/oauth2)

**Comment by awagener** [comment]
Xero have now released their own Ruby SDK if it helps anyone - https://developer.xero.com/documentation/libraries/using-the-xero-api-with-ruby & https://github.com/XeroAPI/xero-ruby

**Comment by pareeohnos** [comment]
What will the official Xero gem mean for Xeroizer? We need OAuth 2 support, but I'm reluctant to migrate to the official gem as that's going to be a lot of work for us and there are some features it doesn't have (like automatically waiting for a period of time if you hit the rate limit) which we rely on. But since we have no choice but to migrate to OAuth 2, I'm concerned that this will mean Xeroizer will get deprecated

**Comment by karosk9** [comment]
Same concerns as above. When do you expect to introduce OAuth 2.0 support for Xeroizer?

**Comment by parndt** [comment]
#500 is working toward this

**Comment by joegaudet** [comment]
Hey all, great work on the gem, I was wondering in the short term, if we manage the oath loop our selves if there's a hack to have the gem use the token we manually manage. I've been experimenting with the official gem, but it doesn't feel ready for prime time yet.

**Comment by CloCkWeRX** [comment]
Should be available on master, please do test it out for your use cases and raise any further bugs :)

**Comment by mcfiredrill** [comment]
Are there any docs for how to use oauth 2.0 on master? I could make a PR once I figure it out.
