### ISSUE TITLE
New gem release?

### ISSUE THREAD

**Issue by ssaunier** [waynerobinson/xeroizer#540]
Hello 👋 ,

First of all thank you for your work on this gem, very helpful 🙏 !

I see that the last release `2.20.0` is 2 years old on Rubygems (https://rubygems.org/gems/xeroizer), do you plan releasing a new version of `master` anytime soon?

Thanks!

**Comment by kitebuggy** [comment]
I concur - especially as Custom Connections are replacing private connectors by end of this month (my PR is awaiting review to address this).  

Of course, Xero themselves have their own gem, which may be playing a part in the decision making process.  However, if that's the case and we're expected to migrate, shouldn't this gem be marked as EOL?

**Comment by rjaus** [comment]
Hey, this SDK has always been a predominately community effort.  Xero has been more involved in the past, but since the new wrappers have been released the focus has shifted away from this one.  The new wrappers are generated from an OpenAPI spec.

While we don't put resources towards it, there is absolutely no intention to hold back the community here.  There has been some turnover in the team, and I believe no one is actually in control of the RubyGems account at present.

I'm currently contracting with Xero, so I can hunt down access to RubyGems and push out a new release. 

Going forward it would make sense for someone from the community to have access to RubyGems to push out releases.  @CloCkWeRX do you want to suggest someone? or yourself?

**Comment by kitebuggy** [comment]
Thanks for the PR merge @rjaus and thanks for the update @CloCkWeRX. Any ideas on how to push this new version out before the Private Apps are EOL'd at the end of this month, please?

**Comment by rjaus** [comment]
@CloCkWeRX thanks for the update mate, good luck with the new role! Your frequent contributions will be sorely missed.  Stop by any time :)

@kitebuggy still aiming for a release shortly.  Should get it done this week.

**Comment by rjaus** [comment]
It's live: https://rubygems.org/gems/xeroizer/versions/3.0.0
